# -*- coding: utf-8 -*-
"""Image_to_text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQ9SQxvCrMaO4fEOdL2TU3p4aDwARlkB
"""

#Libraries to Installed 
!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil

try:
 from PIL import Image
except ImportError:
 import Image

image_path_in_colab="test2.jpg"
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)